//
// Updated on 01/10/25.
// Copyright © 2024. All rights reserved.///
/// @Generated by Mockolo
///

import Foundation
import TracePointKit

public class TracePointKitMock: TracePointKit {
  // MARK: Lifecycle

  public init() {}

  // MARK: Public

  public private(set) var inforCallCount = 0
  public var inforHandler: ((String, String) -> Void)?
  public private(set) var warningCallCount = 0
  public var warningHandler: ((String, String) -> Void)?
  public private(set) var errorCallCount = 0
  public var errorHandler: ((String, String) -> Void)?
  public private(set) var successCallCount = 0
  public var successHandler: ((String, String) -> Void)?

  public func infor(_ tag: String, _ message: String) {
    inforCallCount += 1
    if let inforHandler {
      inforHandler(tag, message)
    }
  }

  public func warning(_ tag: String, _ message: String) {
    warningCallCount += 1
    if let warningHandler {
      warningHandler(tag, message)
    }
  }

  public func error(_ tag: String, _ message: String) {
    errorCallCount += 1
    if let errorHandler {
      errorHandler(tag, message)
    }
  }

  public func success(_ tag: String, _ message: String) {
    successCallCount += 1
    if let successHandler {
      successHandler(tag, message)
    }
  }
}
